version: 2
updates:
  # dotnet tools
  - package-ecosystem: "nuget"
    directory: "/.config"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  # Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:java"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/_scripts/templates/CSharp"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:csharp-standard"
  # JavaScript
  - package-ecosystem: "npm"
    directory: "/_scripts/templates/JavaScript"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:javascript"
  # PHP
  - package-ecosystem: "composer"
    directory: "/_scripts/templates/PHP"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:php"
  # Python3
  - package-ecosystem: "pip"
    directory: "/_scripts/templates/Python3"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:python3"
  # TypeScript
  - package-ecosystem: "npm"
    directory: "/_scripts/templates/TypeScript"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:typescript"
