int foo();
int foo( short s );
int foo( short int si );
int foo( signed short ss );
int foo( signed short int ssi);
int foo( unsigned short us );
int foo( unsigned short int usi );
int foo( int i);
int foo( signed s );
int foo( signed int si );
int foo( unsigned u );
int foo( unsigned int ui );
int foo( long l );
int foo( long int li );
int foo( signed long sl );
int foo( signed long int sli );
int foo( unsigned long ul );
int foo( unsigned long int uli );
int foo( long long ll );
int foo( long long int lli );
int foo( signed long long sll );
int foo( signed long long int slli );
int foo( unsigned long long ull );
int foo( unsigned long long int ulli );
int foo( double d );
int foo( long double ld );
int foo( unsigned long );
int foo( unsigned long int );
int foo( long long );
int foo( long long int );