VERSION 1.0 CLASS
BEGIN
    MultiUse = -1  'True
END
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Name = "ClassDeclarations"
Public Event Ev(ByVal Data As Variant)
Const Foo1 = 2
Private Const Foo3 As [String] = "4"
Private Const Foo2 = 1
Attribute Foo2.VB_VarHelpID = -1
Public Function Foo() as Bar: End Function
Attribute Foo.VB_UserMemId = -4
