GRANT ALL ON tbl TO admin@localhost;
GRANT ALL ON tbl TO admin;
GRANT ALL PRIVILEGES ON tbl TO admin;
GRANT ALL ON *.* TO admin;
GRANT ALL ON *.* TO `admin`;
GRANT ALL ON *.* TO 'admin';
GRANT ALL ON *.* TO "admin";
GRANT ALL ON db.* TO "admin";
GRANT ALL on db.tbl to 'admin';
GRANT ALL on `db`.`tbl` to 'admin';
GRANT ALL on `db`.tbl to 'admin';
GRANT ALL on db.`tbl` to 'admin';
