alter account a drop old url;
alter api integration ai set enabled = false;
alter connection c primary;
alter database d RENAME TO d2;
alter external table et refresh;
alter failover group fg rename to fg2;
alter file format ff RENAME TO ff2;
alter function f() RENAME TO f2;
alter masking policy mp rename to mp2;
alter materialized view mv rename to mv2;
alter network policy np rename to np2;
alter notification integration ni set enabled = false notification_provider = gcp_pubsub gcp_pubsub_subscription_name = '';
alter pipe p REFRESH ;
alter procedure pr() RENAME TO p2;
alter replication group rg rename to rg2;
alter resource monitor rm set credit_quota = 1;
alter role r RENAME TO r2;
alter row access policy rap rename to rap2;
alter schema sch rename to sch2;
alter security integration si set enabled = true;
-- alter security integration snowflake oauth ;
-- alter security integration saml2 ;
-- alter security integration scim ;
alter sequence seq rename to seq2;
alter session set autocommit = true;
alter session policy sp rename to sp2;
alter share sh unset comment;
alter stage stg rename to stg2;
alter storage integration si set enabled = true;
alter stream st unset comment ;
alter table t rename to t2;
alter table t drop c;
alter tag tg rename to tg2;
alter task ts suspend ;
alter user u reset password ;
alter view vw set secure ;
alter warehouse wh suspend ;
alter sequence seq set ORDER COMMENT ='A comment';
alter sequence seq set NOORDER;
