comment on database d is 'd';
comment on file format f is 'f';
comment on function f is 'f';
comment on function f2(int, number) is 'f';
comment on integration i is 'i';
comment on masking policy m is 'm';
comment on network policy n is 'n';
comment on pipe p is 'p';
comment on procedure p is 'p';
comment on role r is 'r';
comment on row access policy r is 'r';
comment on schema s is 's';
comment on sequence s is 's';
comment on session policy s is 's';
comment on stage s is 's';
comment on stream s is 's';
comment on table t is 't';
comment on tag t is 't';
comment on task t is 't';
comment on user u is 'u';
comment on view v is 'v';
comment on warehouse w is 'w';
comment on column t.c IS 't.c';
comment on column s.t.c IS 's.t.c';
comment on column d.s.t.c IS 'd.s.t.c';
