CREATE VIEW RAW.ViewName AS Select MyField FROM RAW.TABLE1;
create view v as select 1 as c;
CREATE VIEW RAW.ViewName AS WITH src AS (Select MyField FROM RAW.TABLE1 WHERE MyField IS NOT NULL) SELECT MyField FROM SRC;
CREATE VIEW V1 (C1 COMMENT 'TEST') AS SELECT 1 as C1;
CREATE VIEW V1 (C1) AS SELECT 1 as C1;
CREATE VIEW VC AS SELECT 1 as c, 2 as d,;
CREATE OR REPLACE VIEW V_MASK (C1, C2 WITH MASKING POLICY MY_POLICY USING (C2, C1)) AS SELECT 1 AS C1, 2 AS C2;
CREATE VIEW V_MASK2 (C1 COMMENT 'plain', C2 WITH MASKING POLICY MY_POLICY COMMENT 'masked') AS SELECT 1 AS C1, 2 AS C2;
