CREATE FILE FORMAT TESTEMPTY;
--Line below is OK in UI
--CREATE FILE FORMAT FMT_CSV_ANSI TYPE = 'CSV' FIELD_DELIMITER = ';' 	SKIP_HEADER = 1 TRIM_SPACE = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = NONE NULL_IF = ('') ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE 	ESCAPE = NONE 	ESCAPE_UNENCLOSED_FIELD = NONE 	ENCODING = WINDOWS1252;
CREATE FILE FORMAT FMT_XML TYPE = 'XML'  COMPRESSION = 'AUTO'   PRESERVE_SPACE = FALSE  STRIP_OUTER_ELEMENT = TRUE   DISABLE_SNOWFLAKE_DATA = FALSE      DISABLE_AUTO_CONVERT = FALSE     IGNORE_UTF8_ERRORS = FALSE;
CREATE FILE FORMAT FMT_CSV_UTF8_PIPE FIELD_DELIMITER = '|' SKIP_HEADER = 1 ESCAPE_UNENCLOSED_FIELD = 'NONE' TRIM_SPACE = TRUE NULL_IF = ('') ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE ;
CREATE FILE FORMAT FMT_CSV_ANSI_BS FIELD_DELIMITER = '\b' SKIP_HEADER = 1 ESCAPE_UNENCLOSED_FIELD = 'NONE' TRIM_SPACE = TRUE NULL_IF = ('') ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE ENCODING = 'WINDOWS1252' ;
-- Below will fail but don't know how to fix it. Seems CHAR_LITERAL is superseeded by STRING
CREATE FILE FORMAT FMT_CSVZIP SKIP_HEADER = 1 TRIM_SPACE = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '\"' NULL_IF = ('') COMPRESSION = BZ2 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE REPLACE_INVALID_CHARACTERS = TRUE ENCODING = 'utf8' ;
