CREATE VIEW RAW.ViewName AS Select MyField FROM RAW.TABLE1;
create view v as select 1 as c;
CREATE VIEW RAW.ViewName AS WITH src AS (Select MyField FROM RAW.TABLE1 WHERE MyField IS NOT NULL) SELECT MyField FROM SRC;
CREATE VIEW V1 (C1 COMMENT 'TEST') AS SELECT 1 as C1;
CREATE VIEW V1 (C1) AS SELECT 1 as C1;