describe database obj;
describe table obj;
describe table obj type = columns ;
describe external table obj;
describe external table obj type = columns;
describe file format obj;
describe function obj();
describe function obj(int);
describe function obj(int, string);
describe integration obj;
describe masking policy obj;
describe materialized view obj;
describe network policy obj;
describe pipe obj;
describe procedure obj();
describe procedure obj(int);
describe procedure obj(string, int);
describe result '00-00';
describe row access policy obj;
describe schema obj;
describe search optimization on obj;
describe sequence obj;
describe session policy obj;
describe share obj;
describe stage obj;
describe stream obj;
describe table db.sch.obj;
describe table sch.obj;
describe table obj;
describe task obj;
describe transaction 1;
describe user obj;
describe view db.sch.obj;
describe view sch.obj;
describe view obj;
describe warehouse obj;
