drop connection obj;
drop database obj;
drop database obj cascade;
drop external table obj;
drop failover group obj;
drop file format obj;
drop function obj();
drop function obj(int);
drop integration obj;
drop managed account obj;
drop masking policy obj;
drop materialized view obj;
drop network policy obj;
drop pipe obj;
drop procedure obj();
drop procedure obj(int);
drop replication group obj;
drop resource monitor obj;
drop role obj;
drop row access policy obj;
drop schema obj;
drop schema obj restrict;
drop sequence obj;
drop session policy obj;
drop share obj;
drop stage obj;
drop stream obj;
drop table obj;
drop tag obj;
drop task obj;
drop user obj;
drop view obj;
drop warehouse obj;
