CREATE OR REPLACE GIT REPOSITORY db.sch.repo1
API_INTEGRATION = git_api_integration
GIT_CREDENTIALS = db.sch.git_secret
ORIGIN = 'https://github.com/my-account/repo-name.git';

DESC GIT REPOSITORY repo1;
DESCRIBE GIT REPOSITORY repo1;
DESCRIBE GIT REPOSITORY sch.repo1;
DESCRIBE GIT REPOSITORY db.sch.repo1;

SHOW GIT BRANCHES IN db.sch.r1;
SHOW GIT BRANCHES IN sch.r1;
SHOW GIT BRANCHES IN r1;
SHOW GIT BRANCHES IN GIT REPOSITORY r1;
SHOW GIT BRANCHES LIKE 'feat%' IN r1;
SHOW GIT BRANCHES LIKE 'feat%' IN GIT REPOSITORY r1;

SHOW GIT REPOSITORIES;
SHOW GIT REPOSITORIES IN ACCOUNT;
SHOW GIT REPOSITORIES LIKE 'r%' IN ACCOUNT;
SHOW GIT REPOSITORIES IN DATABASE;
SHOW GIT REPOSITORIES IN DATABASE db;
SHOW GIT REPOSITORIES IN SCHEMA;
SHOW GIT REPOSITORIES IN SCHEMA db.sch;
SHOW GIT REPOSITORIES IN SCHEMA sch;
SHOW GIT REPOSITORIES IN db.sch;
SHOW GIT REPOSITORIES IN sch;

SHOW GIT TAGS IN r1;
SHOW GIT TAGS IN sch.r1;
SHOW GIT TAGS IN db.sch.r1;
SHOW GIT TAGS IN GIT REPOSITORY r1;
SHOW GIT TAGS LIKE 'rel%' IN r1;
SHOW GIT TAGS LIKE 'rel%' IN GIT REPOSITORY r1;

ALTER GIT REPOSITORY r1 SET GIT_CREDENTIALS = sn;
ALTER GIT REPOSITORY r1 SET API_INTEGRATION = iname;
ALTER GIT REPOSITORY r1 SET COMMENT = 'text';

ALTER GIT REPOSITORY sch.r1 SET TAG t1 = '<tag_value>', t2 = '<tag_value>';
ALTER GIT REPOSITORY r1 UNSET TAG t1, r2;

ALTER GIT REPOSITORY db.sch.r1 UNSET GIT_CREDENTIALS;
ALTER GIT REPOSITORY r1 UNSET COMMENT;

ALTER GIT REPOSITORY r1 FETCH;

DROP GIT REPOSITORY r1;
DROP GIT REPOSITORY sch.r1;
DROP GIT REPOSITORY db.sch.r1;
DROP GIT REPOSITORY IF EXISTS r1;
