copy into t from @stage/;
copy into @stage/ from t;
commit ;
execute immediate 'select 1';
execute task tsk;
explain select 1 as c;
get @stage/a/c file:///tmp/load;
grant ownership on table t to role r;
grant all on account to role r;
grant usage on database d to share s;
grant role r to role r2;
list @stage/;
put file:///tmp/load @stage;
remove @stage/;
remove @stage/x/y/;
remove @sch1.stage/x/y/;
remove @sch1%tblstage/x/y/;
remove @~/x/y/z/;
remove @~/;
revoke usage on database d from role r1;
revoke usage on database d from share sh;
revoke role r from role t1;
rollback ;
set i=1;
truncate materialized view v;
truncate table t;
unset i;
unset (i,j,k);
get @stage/ file://C:\temp\load;
put file://C:\temp\load @stage;
get @sch1%tbl1 file:///tmp/load;
get @sch1%tbl1/x/y/z file:///tmp/load;
GET @%mytable file:///tmp/data/;
GET @%mytable/x/y/z file:///tmp/data/;
GET @~/myfiles file:///tmp/data/;
GET @~/myfiles/x/y/z file:///tmp/data/;
