--SQL test for PASSWORD policy related
CREATE PASSWORD POLICY mypol;
CREATE OR REPLACE PASSWORD POLICY "_mypol";
CREATE PASSWORD POLICY IF NOT EXISTS admin.mypol;
CREATE PASSWORD POLICY TEST_PASSWORD_POL PASSWORD_MIN_LENGTH  = 20 PASSWORD_MIN_UPPER_CASE_CHARS  = 10 PASSWORD_MIN_AGE_DAYS = 1 COMMENT = 'Test PASSWORD';
CREATE PASSWORD POLICY TEST_PASSWORD_POL COMMENT = 'Test PASSWORD 2'  PASSWORD_MIN_UPPER_CASE_CHARS = 20 PASSWORD_MIN_AGE_DAYS = 10;
CREATE PASSWORD POLICY TEST_PASSWORD_POL COMMENT = 'Test PASSWORD 3';

ALTER PASSWORD POLICY mypol UNSET PASSWORD_MIN_UPPER_CASE_CHARS;
ALTER PASSWORD POLICY mypol SET PASSWORD_MIN_AGE_DAYS = 20 PASSWORD_MIN_UPPER_CASE_CHARS = 20;
ALTER PASSWORD POLICY IF EXISTS mypol UNSET COMMENT;
ALTER PASSWORD POLICY IF EXISTS mypol RENAME TO myPol2;
ALTER PASSWORD POLICY IF EXISTS mypol SET TAG MyTag = 'aValue';
ALTER PASSWORD POLICY IF EXISTS mypol UNSET TAG MyTag;

DROP PASSWORD POLICY mypol;
DROP PASSWORD POLICY IF EXISTS mypol;