show columns like 'na%';
show channels;
show channels in account;
show channels in database;
show channels in database d1;
show channels like 'c1%';
show channels like 'c1%' in account;
show channels like 'c1%' in database;
show channels like 'c1%' in database d1;

show connections like 'na%';
show databases like 'na%';
show databases in failover group grp;
show databases in replication group grp;
show delegated authorizations;
show external functions like 'na%';
show external tables like 'na%';
show failover groups ;
show file formats like 'na%';
show functions like 'na%';
show global accounts like 'na%';
show grants on account ;
show integrations like 'na%';
show locks ;
show managed accounts like 'na%';
show masking policies like 'na%';
show materialized views like 'na%';
show network policies;
show objects like 'na%';
show organization accounts like 'na%';
show parameters like 'na%';
show pipes like 'na%';
show primary keys ;
show procedures like 'na%';
show regions like 'na%';
show replication accounts like 'na%';
show replication databases like 'na%';
show replication groups;
show resource monitors like 'na%';
show roles like 'na%';
show row access policies like 'na%';
show schemas like 'na%';
show sequences like 'na%';
show session policies;
show shares like 'na%';
show shares in failover group grp;
show shares in replication group grp;
show stages like 'na%';
show streams like 'na%';
show tables like 'na%';
show tags like 'na%';
show tasks like 'na%';
show transactions ;
show user functions like 'na%';
show users like 'na%';
show variables like 'na%';
show views like 'na%';
show warehouses like 'na%';
