UPDATE #TEMP_DG_RIPO
SET UEBERGEORDNETE_HANDELSSTELLE_NAME = H.BEZEICHNUNG_DE
FROM #TEMP_DG_RIPO R
  LEFT JOIN DM.VW_DM_PR_HANDELSSTELLE H WITH (NOLOCK) ON H.HANDELSSTELLE = R.UEBERGEORDNETE_HANDELSSTELLE_NUMMER
