SELECT F
FROM (SELECT 1 AS F) AS T
FOR JSON AUTO, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES;
GO;

-- With another order of options
SELECT F
FROM (SELECT 1 AS F) AS T
FOR JSON AUTO, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER;
GO;

-- Without additional options
SELECT F
FROM (SELECT 1 AS F) AS T
FOR JSON AUTO;
GO;

-- With ROOT
SELECT F
FROM (SELECT 1 AS F) AS T
FOR JSON AUTO, INCLUDE_NULL_VALUES, ROOT('r');
GO;