CREATE PARTITION FUNCTION myRangePF1(DATETIME)
AS RANGE RIGHT
FOR VALUES ('20200101');
ALTER PARTITION FUNCTION myRangePF1 ()  
MERGE RANGE (100);  
ALTER PARTITION FUNCTION myRangePF1 ()  
SPLIT RANGE (500); 
