-- Creating a Simple Queue Table
CREATE SET TABLE qtbl_1, QUEUE, FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL (
    col_1 TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    col_2 INTEGER,
    col_3 INTEGER)
PRIMARY INDEX (col_2, col_3);

-- Creating a Multiset Queue Table
CREATE MULTISET TABLE qtbl_3, QUEUE,
NO BEFORE JOURNAL,
NO AFTER JOURNAL (
    qits TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    col_2 INTEGER,
    col_3 INTEGER CHECK (col_3 > 10))
PRIMARY INDEX (qits);
