INSERT INTO CUSTOMERS_TEST (ID,CUSTOMER_MEMBERSHIP_DURATION,CUSTOMER_CALL_DURATION) VALUES (1

--, INTERVAL '1-6' YEAR TO MONTH
--, INTERVAL '0 02:30:00' YEAR TO MONTH
, INTERVAL '0 02:30:00' DAY TO SECOND(2)

)
;