alter role TEST_ROLE_AAA NOT IDENTIFIED;

alter role TEST_ROLE_AAA  IDENTIFIED BY data;

alter role TEST_ROLE_AAA  IDENTIFIED EXTERNALLY;

ALTER ROLE TEST_ROLE_AAA IDENTIFIED USING hr.admin;

alter role TEST_ROLE_AAA  IDENTIFIED GLOBALLY;


