ALTER TABLE test1 SPLIT PARTITION p_MAXV
    AT (TO_DATE('01/01/2030', 'DD/MM/YYYY'))
    INTO (partition p_2029 TABLESPACE users, partition p_MAXV) ONLINE;

ALTER TABLE NAV.SPAC_AUT_APOLICE MODIFY SUBPARTITION P12345 SHRINK SPACE CHECK;