CREATE OR REPLACE VIEW VIEW_TEST_ROLE AS
SELECT ID, NAME || '-' ALIAS_NAME
FROM TEST_ROLE
WHERE ID < 6 with check option;

CREATE OR REPLACE FORCE VIEW VIEW_TEST_ROLE AS
SELECT ID, NAME || '-' ALIAS_NAME
FROM TEST_ROLE
WHERE ID < 7 with check option;

CREATE OR REPLACE NOFORCE VIEW VIEW_TEST_ROLE AS
SELECT ID, NAME || '-' ALIAS_NAME
FROM TEST_ROLE
WHERE ID < 8 with check option;
