CREATE OR REPLACE EDITIONABLE TRIGGER editionable_trg
BEFORE INSERT ON my_table
FOR EACH ROW
BEGIN
    NULL;
END;
/

CREATE OR REPLACE NONEDITIONABLE TRIGGER noneditionable_trg
BEFORE INSERT ON my_table
FOR EACH ROW
BEGIN
    NULL;
END;
/
