SELECT AVG(SALARY) OVER (PARTITION BY JOB_ID) FROM HR.EMPLOYEES;
SELECT SUM(SALARY) OVER (PARTITION BY JOB_ID) FROM HR.EMPLOYEES;
SELECT MAX(SALARY) OVER (PARTITION BY JOB_ID) FROM HR.EMPLOYEES;
SELECT MIN(SALARY) OVER (PARTITION BY JOB_ID) FROM HR.EMPLOYEES;
SELECT COUNT(SALARY) OVER (PARTITION BY JOB_ID) FROM HR.EMPLOYEES;
