CREATE TABLE foo (bar text, baz text);
ALTER TABLE foo RENAME TO foobar;
ALTER TABLE foobar RENAME COLUMN baz TO qux;
ALTER TABLE foobar ADD COLUMN quux text;
ALTER TABLE foobar ADD CONSTRAINT quuz CHECK (quux IS NOT NULL);
ALTER TABLE foobar DROP CONSTRAINT quuz;
ALTER TABLE foobar DROP COLUMN quux;
ALTER TABLE foobar ALTER COLUMN qux SET NOT NULL;
ALTER TABLE foobar ALTER COLUMN qux DROP NOT NULL;