SELECT FIRST_VALUE(c2) OVER ( ORDER BY c3 ROWS UNBOUNDED PRECEDING EXCLUDE NO OTHERS ) AS c FROM t;
SELECT FIRST_VALUE(c2) OVER ( ORDER BY c3 ROWS UNBOUNDED PRECEDING EXCLUDE CURRENT ROW ) AS c FROM t;
SELECT FIRST_VALUE(c2) OVER ( ORDER BY c3 ROWS UNBOUNDED PRECEDING EXCLUDE GROUP ) AS c FROM t;
SELECT FIRST_VALUE(c2) OVER ( ORDER BY c3 ROWS UNBOUNDED PRECEDING EXCLUDE TIES ) AS c FROM t;
