CREATE TABLE t1(ts TIMESTAMP, c1 INT);

CREATE TABLE IF NOT EXISTS test.t1(
    ts TIMESTAMP, c1 INT, c2 INT UNSIGNED, c3 BIGINT, c4 BIGINT UNSIGNED, c5 FLOAT, c6 DOUBLE, c7 BINARY(20),
    c8 SMALLINT, c9 SMALLINT UNSIGNED, c10 TINYINT, c11 TINYINT UNSIGNED, c12 BOOL,
    c13 NCHAR(30), c15 VARCHAR(50))
    TTL 100 COMMENT 'test create table' SMA(c1, c2, c3);

CREATE TABLE IF NOT EXISTS rollup_db.t1(
    ts TIMESTAMP, c1 INT, c2 INT UNSIGNED, c3 BIGINT, c4 BIGINT UNSIGNED, c5 FLOAT, c6 DOUBLE, c7 BINARY(20),
    c8 SMALLINT, c9 SMALLINT UNSIGNED, c10 TINYINT, c11 TINYINT UNSIGNED, c12 BOOL,
    c13 NCHAR(30), c14 VARCHAR(50))
    TAGS (a1 TIMESTAMP, a2 INT, a3 INT UNSIGNED, a4 BIGINT, a5 BIGINT UNSIGNED, a6 FLOAT, a7 DOUBLE, a8 BINARY(20),a9 SMALLINT, a10 SMALLINT UNSIGNED, a11 TINYINT, a12 TINYINT UNSIGNED, a13 BOOL, a14 NCHAR(30), a15 VARCHAR(50))
    COMMENT 'test create table' SMA(c1, c2, c3) ROLLUP (MIN);

CREATE TABLE IF NOT EXISTS t1 USING st1 TAGS(1, 'wxy', NOW);

CREATE TABLE IF NOT EXISTS test.t1 USING test.st1 (tag1, tag2) TAGS(1, 'abc') IF NOT EXISTS test.t2 USING test.st1 (tag1, tag2) TAGS(2, 'abc') IF NOT EXISTS test.t3 USING test.st1 (tag1, tag2) TAGS(3, 'abc');

CREATE TABLE IF NOT EXISTS t1 USING st1 TAGS(1, 'wxy', NOW + 1S);