--SHOW SPECIFIC FUNCTION
SHOW SPECIFIC FUNCTION udf_1;

--SHOW FUNCTION
SHOW FUNCTION udf2 (INTEGER, INTEGER);

-- SHOW CAST
SHOW CAST sysudtlib.SomeUdt1;

-- SHOW Avro SCHEMA
SHOW Avro SCHEMA salesDatasetSchema;

-- SHOW FOREIGN SERVER
SHOW FOREIGN SERVER td_server_db.presto1;
