<?target?>
<?ws?>
<?target ?>
<?target ordinary text?>
<?target ? leading question?>
<?target body? middle?? trailing???>
<?target
multiline body
?>
Start ::= 'x' <?inline body?> Item
Item ::= 'y'
<?TOKENS?>
Token ::= [a-z]+
<?ENCORE?>
<?after?>
