GRANT INSERT, DELETE ON t TO u;
GRANT UPDATE ON t TO u;
GRANT SELECT ON t TO ROLE PUBLIC WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE t TO USER u;
GRANT DELETE ON "t" TO ROLE "public" WITH GRANT OPTION;
GRANT SELECT ON SCHEMA s TO USER u;
