PREPARE myquery FROM SELECT ?, ? FROM foo;
PREPARE myquery FROM SELECT * FROM foo LIMIT ?;
PREPARE myquery FROM SELECT ?, ? FROM foo LIMIT ?;
PREPARE myquery FROM SELECT ? FROM foo FETCH FIRST ? ROWS ONLY;
PREPARE myquery FROM SELECT ?, ? FROM foo FETCH NEXT ? ROWS WITH TIES;
PREPARE myquery FROM SELECT ?, ? FROM foo OFFSET ? ROWS;
PREPARE myquery FROM SELECT ? FROM foo OFFSET ? ROWS LIMIT ?;
PREPARE myquery FROM SELECT ? FROM foo OFFSET ? ROWS FETCH FIRST ? ROWS WITH TIES;
