ALTER TABLE foo.t RENAME COLUMN a TO b;
ALTER TABLE IF EXISTS foo.t RENAME COLUMN a TO b;
ALTER TABLE foo.t RENAME COLUMN IF EXISTS a TO b;
ALTER TABLE IF EXISTS foo.t RENAME COLUMN IF EXISTS a TO b;
