ALTER TABLE a SET PROPERTIES foo='bar';
ALTER TABLE a SET PROPERTIES foo=true;
ALTER TABLE a SET PROPERTIES foo=123;
ALTER TABLE a SET PROPERTIES foo=123, bar=456;
ALTER TABLE a SET PROPERTIES " s p a c e "='bar';
ALTER TABLE a SET PROPERTIES foo=123, bar=DEFAULT;
