-- BA210050.A
--
--                             Grant of Unlimited Rights
--
--     The Ada Conformity Assessment Authority (ACAA) holds unlimited
--     rights in the software and documentation contained herein. Unlimited
--     rights are the same as those granted by the U.S. Government for older
--     parts of the Ada Conformity Assessment Test Suite, and are defined
--     in DFAR 252.227-7013(a)(19). By making this public release, the ACAA
--     intends to confer upon all recipients unlimited rights equal to those
--     held by the ACAA. These rights include rights to use, duplicate,
--     release or disclose the released technical data and computer software
--     in whole or in part, in any manner and for any purpose whatsoever, and
--     to have or permit others to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS. THE ACAA MAKES NO EXPRESS OR IMPLIED
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--
--                                     Notice
--
--     The ACAA has created and maintains the Ada Conformity Assessment Test
--     Suite for the purpose of conformity assessments conducted in accordance
--     with the International Standard ISO/IEC 18009 - Ada: Conformity
--     assessment of a language processor. This test suite should not be used
--     to make claims of conformance unless used in accordance with
--     ISO/IEC 18009 and any applicable ACAA procedures.
--
--*
-- OBJECTIVE:
--     Check that the categorization aspects Pure and Preelaborate cannot
--     be specified by a value declared in the same package.
--
--     Check that the categorization aspects Pure and Preelaborate cannot
--     be specified by a nonstatic value.
--
--     Check that the categorization aspects Pure and Preelaborate are
--     specified by a value of type Boolean.
--
-- TEST DESCRIPTION:
--     We use the general organization of CA21002.
--
--     The first objective comes from Corrigendum 1 (via AI12-0154-1);
--     the actual wording is in 13.1.1(32/4). The second and third objective
--     also comes from 13.1.1(32/4). We want to test these objectives for
--     each aspect that corresponds to a library unit pragma.
--
-- TEST FILES:
--      This test consists of the following files:
--      -> BA210050.A
--         BA210051.A
--         BA210052.A
--         BA210053.A
--         BA210054.A
--         BA210055.A
--         BA210056.A
--         BA210057.AM
--
-- PASS/FAIL CRITERIA:
--      Files BA210051.A, BA210052.A, BA210053.A, BA210054.A, BA210055.A,
--      and BA210056.A contain errors. All errors in these files must be
--      detected to pass the test. Compiling the body file BA210057.AM
--      is optional.
--
-- CHANGE HISTORY:
--     22 Mar 2017  RLB  Created test.
--
--!
package BA210050 with Preelaborate => True is
   type New_Bool is new Boolean;
   Is_Pure_Funny     : constant New_Bool := False;
   Is_Pure_Dynamic   : Boolean := True;
   Is_Preelab_Funny  : constant Integer := 1;
   Is_Preelab_Dynamic: Boolean := True;
end BA210050;

