drop function f1;
drop index i1 ;
drop procedure p1;
drop role r1;
drop schema s1 restrict ;
drop sequence se1 restrict ;
drop synonym sy1;
drop table t1;
drop trigger tr1;
drop type ty1 restrict ;
drop view v1;
