"""
Rename XPath4Parser.g4 parser rule names from all-lowercase to lowerCamelCase,
matching the spec's PascalCase names (just lowercase the first letter).
"""
import re, sys

# Mapping: current name -> new lowerCamelCase name
# Derived from spec PascalCase by lowercasing the first character.
# Multi-letter leading acronyms (EQ, URI) are treated as a unit and lowercased.
RENAMES = {
    "abbreviatedstep":             "abbreviatedStep",
    "absolutepathexpr":            "absolutePathExpr",
    "additiveexpr":                "additiveExpr",
    "andexpr":                     "andExpr",
    "anyarraytype":                "anyArrayType",
    "anyfunctiontype":             "anyFunctionType",
    "anyitemtype":                 "anyItemType",
    "anymaptype":                  "anyMapType",
    "anyrecordtype":               "anyRecordType",
    "anyxnodetype":                "anyXNodeType",
    "argumentlist":                "argumentList",
    "argumentplaceholder":         "argumentPlaceholder",
    "arrayconstructor":            "arrayConstructor",
    "arraytype":                   "arrayType",
    "arrowexpr":                   "arrowExpr",
    "arrowtarget":                 "arrowTarget",
    "attributename":               "attributeName",
    "attributenodetype":           "attributeNodeType",
    "axisstep":                    "axisStep",
    "bracedaction":                "bracedAction",
    "castableexpr":                "castableExpr",
    "castexpr":                    "castExpr",
    "casttarget":                  "castTarget",
    "choiceitemtype":              "choiceItemType",
    "commentnodetype":             "commentNodeType",
    "comparisonexpr":              "comparisonExpr",
    # mixed-case names already in file -- normalise all to spec-derived form
    "compAttrconstructor":         "compAttrConstructor",
    "compCommentconstructor":      "compCommentConstructor",
    "compdocconstructor":          "compDocConstructor",
    "compElemconstructor":         "compElemConstructor",
    "compNSconstructor":           "compNamespaceConstructor",
    "compnodename":                "compNodeName",
    "compnodencname":              "compNodeNCName",
    "compPIconstructor":           "compPIConstructor",
    "comptextconstructor":         "compTextConstructor",
    "computedconstructor":         "computedConstructor",
    "contextvalueref":             "contextValueRef",
    "curlyarrayconstructor":       "curlyArrayConstructor",
    "defaultelementnamespacedecl": "defaultElementNamespaceDecl",
    "documentnodetype":            "documentNodeType",
    "dynamicnodetest":             "dynamicNodeTest",
    "elementname":                 "elementName",
    "elementnodetype":             "elementNodeType",
    "enclosedcontentexpr":         "enclosedContentExpr",
    "enclosedexpr":                "enclosedExpr",
    "enumerationtype":             "enumerationType",
    "eqname":                      "eqName",       # EQName
    "exprsingle":                  "exprSingle",
    "fielddeclaration":            "fieldDeclaration",
    "fieldname":                   "fieldName",
    "forbinding":                  "forBinding",
    "forclause":                   "forClause",
    "forentrybinding":             "forEntryBinding",
    "forentrykeybinding":          "forEntryKeyBinding",
    "forentryvaluebinding":        "forEntryValueBinding",
    "forexpr":                     "forExpr",
    "foritembinding":              "forItemBinding",
    "forletreturn":                "forLetReturn",
    "formemberbinding":            "forMemberBinding",
    "fullstep":                    "fullStep",
    "functionbody":                "functionBody",
    "functioncall":                "functionCall",
    "functionitemexpr":            "functionItemExpr",
    "functionsignature":           "functionSignature",
    "functiontype":                "functionType",
    "generalcomp":                 "generalComp",
    "gnodetype":                   "gNodeType",
    "ifexpr":                      "ifExpr",
    "inlinefunctionexpr":          "inlineFunctionExpr",
    "instanceofexpr":              "instanceofExpr",   # InstanceofExpr (spec: lowercase 'of')
    "intersectexceptexpr":         "intersectExceptExpr",
    "itemtype":                    "itemType",
    "jnodetype":                   "jNodeType",
    "jrootselector":               "jRootSelector",
    "keyspecifier":                "keySpecifier",
    "keywordargument":             "keywordArgument",
    "keywordarguments":            "keywordArguments",
    "letarraybinding":             "letArrayBinding",
    "letbinding":                  "letBinding",
    "letclause":                   "letClause",
    "letexpr":                     "letExpr",
    "letmapbinding":               "letMapBinding",
    "letsequencebinding":          "letSequenceBinding",
    "letvaluebinding":             "letValueBinding",
    "lookupwildcard":              "lookupWildcard",
    "mapconstructor":              "mapConstructor",
    "mapconstructorentry":         "mapConstructorEntry",
    "mappingarrowtarget":          "mappingArrowTarget",
    "maptype":                     "mapType",
    "markedncname":                "markedNCName",
    "multiplicativeexpr":          "multiplicativeExpr",
    "namedfunctionref":            "namedFunctionRef",
    "namespacedecl":               "namespaceDecl",
    "namespacenodetype":           "namespaceNodeType",
    "nametest":                    "nameTest",
    "nametestunion":               "nameTestUnion",
    "nodecomp":                    "nodeComp",
    "nodeConstructor":             "nodeConstructor",  # already camelCase, but normalise
    "nodefollows":                 "nodeFollows",
    "nodeprecedes":                "nodePrecedes",
    "nodetest":                    "nodeTest",
    "numericliteral":              "numericLiteral",
    "occurrenceindicator":         "occurrenceIndicator",
    "orexpr":                      "orExpr",
    "otherwiseexpr":               "otherwiseExpr",
    "paramlist":                   "paramList",
    "parenthesizedexpr":           "parenthesizedExpr",
    "pathexpr":                    "pathExpr",
    "pipelineexpr":                "pipelineExpr",
    "positionalargumentlist":      "positionalArgumentList",
    "positionalarguments":         "positionalArguments",
    "positionalvar":               "positionalVar",
    "postfixexpr":                 "postfixExpr",
    "predicatelist":               "predicateList",
    "primaryexpr":                 "primaryExpr",
    "processinginstructionnodetype": "processingInstructionNodeType",
    "qnameliteral":                "qNameLiteral",
    "quantifiedexpr":              "quantifiedExpr",
    "quantifierbinding":           "quantifierBinding",
    "rangeexpr":                   "rangeExpr",
    "recordputexpr":               "recordPutExpr",
    "recordtype":                  "recordType",
    "regularitemtype":             "regularItemType",
    "relativepathexpr":            "relativePathExpr",
    "restricteddynamiccall":       "restrictedDynamicCall",
    "schemaattributenodetype":     "schemaAttributeNodeType",
    "schemaelementnodetype":       "schemaElementNodeType",
    "sequencearrowtarget":         "sequenceArrowTarget",
    "sequencetype":                "sequenceType",
    "simplemapexpr":               "simpleMapExpr",
    "simplenodetest":              "simpleNodeTest",
    "simpletypename":              "simpleTypeName",
    "squarearrayconstructor":      "squareArrayConstructor",
    "stepexpr":                    "stepExpr",
    "stringconcatexpr":            "stringConcatExpr",
    "stringtemplate":              "stringTemplate",
    "textnodetype":                "textNodeType",
    "treatexpr":                   "treatExpr",
    "typedarraytype":              "typedArrayType",
    "typedeclaration":             "typeDeclaration",
    "typedfunctionparam":          "typedFunctionParam",
    "typedfunctionparamlist":      "typedFunctionParamList",
    "typedfunctiontype":           "typedFunctionType",
    "typedmaptype":                "typedMapType",
    "typedrecordtype":             "typedRecordType",
    "typename_":                   "typeName_",
    "typetest":                    "typeTest",
    "unaryexpr":                   "unaryExpr",
    "unarylookup":                 "unaryLookup",
    "unbracedactions":             "unbracedActions",
    "unionexpr":                   "unionExpr",
    "unionnodetest":               "unionNodeTest",
    "uriliteral":                  "uriLiteral",   # URILiteral
    "valuecomp":                   "valueComp",
    "valueexpr":                   "valueExpr",
    "varnameandtype":              "varNameAndType",
    "varref":                      "varRef",
    "xnodetype":                   "xNodeType",
    "xpath":                       "xPath",
}

def rename_in_file(path):
    with open(path) as f:
        text = f.read()

    # Sort by length descending so longer names are replaced first
    # (prevents partial matches, e.g. "nametest" before "nametestunion")
    for old, new in sorted(RENAMES.items(), key=lambda x: -len(x[0])):
        if old == new:
            continue
        # Replace whole-word occurrences only (not inside other identifiers)
        text = re.sub(r'\b' + re.escape(old) + r'\b', new, text)

    with open(path, "w") as f:
        f.write(text)
    print(f"Renamed in {path}")

rename_in_file("xpath/xpath4/XPath4Parser.g4")
