(define (problem truck-8)
(:domain Trucks-SimplePreferences)
(:objects
	truck1 - truck
	package1 - package
	package2 - package
	package3 - package
	package4 - package
	package5 - package
	package6 - package
	package7 - package
	package8 - package
	package9 - package
	package10 - package
	l1 - location
	l2 - location
	l3 - location
	l4 - location
	t0 - time
	t1 - time
	t2 - time
	t3 - time
	t4 - time
	t5 - time
	t6 - time
	t7 - time
	t8 - time
	t9 - time
	t10 - time
	t11 - time
	t12 - time
	t13 - time
	t14 - time
	t15 - time
	t16 - time
	t17 - time
	t18 - time
	t19 - time
	t20 - time
	a1 - truckarea
	a2 - truckarea
	a3 - truckarea)

(:init
	(at truck1 l1)
	(free a1 truck1)
	(free a2 truck1)
	(free a3 truck1)
	(closer a1 a2)
	(closer a1 a3)
	(closer a2 a3)
	(at package1 l2)
	(at package2 l2)
	(at package3 l2)
	(at package4 l1)
	(at package5 l1)
	(at package6 l1)
	(at package7 l1)
	(at package8 l1)
	(at package9 l1)
	(at package10 l2)
	(connected l1 l2)
	(connected l1 l3)
	(connected l1 l4)
	(connected l2 l1)
	(connected l2 l3)
	(connected l2 l4)
	(connected l3 l1)
	(connected l3 l2)
	(connected l3 l4)
	(connected l4 l1)
	(connected l4 l2)
	(connected l4 l3)
	(time-now t0)
	(le t1 t1)
	(le t1 t2)
	(le t1 t3)
	(le t1 t4)
	(le t1 t5)
	(le t1 t6)
	(le t1 t7)
	(le t1 t8)
	(le t1 t9)
	(le t1 t10)
	(le t1 t11)
	(le t1 t12)
	(le t1 t13)
	(le t1 t14)
	(le t1 t15)
	(le t1 t16)
	(le t1 t17)
	(le t1 t18)
	(le t1 t19)
	(le t1 t20)
	(le t2 t2)
	(le t2 t3)
	(le t2 t4)
	(le t2 t5)
	(le t2 t6)
	(le t2 t7)
	(le t2 t8)
	(le t2 t9)
	(le t2 t10)
	(le t2 t11)
	(le t2 t12)
	(le t2 t13)
	(le t2 t14)
	(le t2 t15)
	(le t2 t16)
	(le t2 t17)
	(le t2 t18)
	(le t2 t19)
	(le t2 t20)
	(le t3 t3)
	(le t3 t4)
	(le t3 t5)
	(le t3 t6)
	(le t3 t7)
	(le t3 t8)
	(le t3 t9)
	(le t3 t10)
	(le t3 t11)
	(le t3 t12)
	(le t3 t13)
	(le t3 t14)
	(le t3 t15)
	(le t3 t16)
	(le t3 t17)
	(le t3 t18)
	(le t3 t19)
	(le t3 t20)
	(le t4 t4)
	(le t4 t5)
	(le t4 t6)
	(le t4 t7)
	(le t4 t8)
	(le t4 t9)
	(le t4 t10)
	(le t4 t11)
	(le t4 t12)
	(le t4 t13)
	(le t4 t14)
	(le t4 t15)
	(le t4 t16)
	(le t4 t17)
	(le t4 t18)
	(le t4 t19)
	(le t4 t20)
	(le t5 t5)
	(le t5 t6)
	(le t5 t7)
	(le t5 t8)
	(le t5 t9)
	(le t5 t10)
	(le t5 t11)
	(le t5 t12)
	(le t5 t13)
	(le t5 t14)
	(le t5 t15)
	(le t5 t16)
	(le t5 t17)
	(le t5 t18)
	(le t5 t19)
	(le t5 t20)
	(le t6 t6)
	(le t6 t7)
	(le t6 t8)
	(le t6 t9)
	(le t6 t10)
	(le t6 t11)
	(le t6 t12)
	(le t6 t13)
	(le t6 t14)
	(le t6 t15)
	(le t6 t16)
	(le t6 t17)
	(le t6 t18)
	(le t6 t19)
	(le t6 t20)
	(le t7 t7)
	(le t7 t8)
	(le t7 t9)
	(le t7 t10)
	(le t7 t11)
	(le t7 t12)
	(le t7 t13)
	(le t7 t14)
	(le t7 t15)
	(le t7 t16)
	(le t7 t17)
	(le t7 t18)
	(le t7 t19)
	(le t7 t20)
	(le t8 t8)
	(le t8 t9)
	(le t8 t10)
	(le t8 t11)
	(le t8 t12)
	(le t8 t13)
	(le t8 t14)
	(le t8 t15)
	(le t8 t16)
	(le t8 t17)
	(le t8 t18)
	(le t8 t19)
	(le t8 t20)
	(le t9 t9)
	(le t9 t10)
	(le t9 t11)
	(le t9 t12)
	(le t9 t13)
	(le t9 t14)
	(le t9 t15)
	(le t9 t16)
	(le t9 t17)
	(le t9 t18)
	(le t9 t19)
	(le t9 t20)
	(le t10 t10)
	(le t10 t11)
	(le t10 t12)
	(le t10 t13)
	(le t10 t14)
	(le t10 t15)
	(le t10 t16)
	(le t10 t17)
	(le t10 t18)
	(le t10 t19)
	(le t10 t20)
	(le t11 t11)
	(le t11 t12)
	(le t11 t13)
	(le t11 t14)
	(le t11 t15)
	(le t11 t16)
	(le t11 t17)
	(le t11 t18)
	(le t11 t19)
	(le t11 t20)
	(le t12 t12)
	(le t12 t13)
	(le t12 t14)
	(le t12 t15)
	(le t12 t16)
	(le t12 t17)
	(le t12 t18)
	(le t12 t19)
	(le t12 t20)
	(le t13 t13)
	(le t13 t14)
	(le t13 t15)
	(le t13 t16)
	(le t13 t17)
	(le t13 t18)
	(le t13 t19)
	(le t13 t20)
	(le t14 t14)
	(le t14 t15)
	(le t14 t16)
	(le t14 t17)
	(le t14 t18)
	(le t14 t19)
	(le t14 t20)
	(le t15 t15)
	(le t15 t16)
	(le t15 t17)
	(le t15 t18)
	(le t15 t19)
	(le t15 t20)
	(le t16 t16)
	(le t16 t17)
	(le t16 t18)
	(le t16 t19)
	(le t16 t20)
	(le t17 t17)
	(le t17 t18)
	(le t17 t19)
	(le t17 t20)
	(le t18 t18)
	(le t18 t19)
	(le t18 t20)
	(le t19 t19)
	(le t19 t20)
	(le t20 t20)
	(next t0 t1)
	(next t1 t2)
	(next t2 t3)
	(next t3 t4)
	(next t4 t5)
	(next t5 t6)
	(next t6 t7)
	(next t7 t8)
	(next t8 t9)
	(next t9 t10)
	(next t10 t11)
	(next t11 t12)
	(next t12 t13)
	(next t13 t14)
	(next t14 t15)
	(next t15 t16)
	(next t16 t17)
	(next t17 t18)
	(next t18 t19)
	(next t19 t20))

(:goal (and 
	(at-destination package1 l1)
	(preference p1A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t3))))
	(preference p2A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t4))))
	(preference p3A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t5))))
	(preference p4A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t6))))
	(preference p5A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t7))))
	(preference p6A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t8))))
	(preference p7A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t9))))
	(preference p8A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t10))))
	(preference p9A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t11))))
	(preference p10A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t12))))
	(preference p11A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t13))))
	(preference p12A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t14))))
	(preference p13A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t15))))
	(preference p14A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t16))))
	(preference p15A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t17))))
	(preference p16A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t18))))
	(preference p17A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t19))))
	(preference p18A (exists (?t - time)
		 (and (delivered package1 l1 ?t) (le ?t t20))))
	(at-destination package2 l1)
	(preference p1B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t3))))
	(preference p2B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t4))))
	(preference p3B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t5))))
	(preference p4B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t6))))
	(preference p5B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t7))))
	(preference p6B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t8))))
	(preference p7B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t9))))
	(preference p8B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t10))))
	(preference p9B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t11))))
	(preference p10B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t12))))
	(preference p11B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t13))))
	(preference p12B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t14))))
	(preference p13B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t15))))
	(preference p14B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t16))))
	(preference p15B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t17))))
	(preference p16B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t18))))
	(preference p17B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t19))))
	(preference p18B (exists (?t - time)
		 (and (delivered package2 l1 ?t) (le ?t t20))))
	(at-destination package3 l3)
	(preference p1C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t3))))
	(preference p2C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t4))))
	(preference p3C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t5))))
	(preference p4C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t6))))
	(preference p5C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t7))))
	(preference p6C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t8))))
	(preference p7C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t9))))
	(preference p8C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t10))))
	(preference p9C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t11))))
	(preference p10C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t12))))
	(preference p11C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t13))))
	(preference p12C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t14))))
	(preference p13C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t15))))
	(preference p14C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t16))))
	(preference p15C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t17))))
	(preference p16C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t18))))
	(preference p17C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t19))))
	(preference p18C (exists (?t - time)
		 (and (delivered package3 l3 ?t) (le ?t t20))))
	(at-destination package4 l2)
	(preference p1D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t6))))
	(preference p2D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t7))))
	(preference p3D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t8))))
	(preference p4D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t9))))
	(preference p5D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t10))))
	(preference p6D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t11))))
	(preference p7D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t12))))
	(preference p8D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t13))))
	(preference p9D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t14))))
	(preference p10D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t15))))
	(preference p11D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t16))))
	(preference p12D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t17))))
	(preference p13D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t18))))
	(preference p14D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t19))))
	(preference p15D (exists (?t - time)
		 (and (delivered package4 l2 ?t) (le ?t t20))))
	(at-destination package5 l4)
	(preference p1E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t6))))
	(preference p2E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t7))))
	(preference p3E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t8))))
	(preference p4E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t9))))
	(preference p5E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t10))))
	(preference p6E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t11))))
	(preference p7E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t12))))
	(preference p8E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t13))))
	(preference p9E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t14))))
	(preference p10E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t15))))
	(preference p11E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t16))))
	(preference p12E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t17))))
	(preference p13E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t18))))
	(preference p14E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t19))))
	(preference p15E (exists (?t - time)
		 (and (delivered package5 l4 ?t) (le ?t t20))))
	(at-destination package6 l4)
	(preference p1F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t6))))
	(preference p2F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t7))))
	(preference p3F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t8))))
	(preference p4F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t9))))
	(preference p5F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t10))))
	(preference p6F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t11))))
	(preference p7F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t12))))
	(preference p8F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t13))))
	(preference p9F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t14))))
	(preference p10F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t15))))
	(preference p11F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t16))))
	(preference p12F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t17))))
	(preference p13F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t18))))
	(preference p14F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t19))))
	(preference p15F (exists (?t - time)
		 (and (delivered package6 l4 ?t) (le ?t t20))))
	(at-destination package7 l3)
	(preference p1G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t9))))
	(preference p2G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t10))))
	(preference p3G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t11))))
	(preference p4G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t12))))
	(preference p5G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t13))))
	(preference p6G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t14))))
	(preference p7G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t15))))
	(preference p8G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t16))))
	(preference p9G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t17))))
	(preference p10G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t18))))
	(preference p11G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t19))))
	(preference p12G (exists (?t - time)
		 (and (delivered package7 l3 ?t) (le ?t t20))))
	(at-destination package8 l3)
	(preference p1H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t9))))
	(preference p2H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t10))))
	(preference p3H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t11))))
	(preference p4H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t12))))
	(preference p5H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t13))))
	(preference p6H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t14))))
	(preference p7H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t15))))
	(preference p8H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t16))))
	(preference p9H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t17))))
	(preference p10H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t18))))
	(preference p11H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t19))))
	(preference p12H (exists (?t - time)
		 (and (delivered package8 l3 ?t) (le ?t t20))))

	(at-destination package9 l3)


	(at-destination package10 l1)
))

(:metric minimize (+ (* 1 (is-violated p1A))
		     (* 1 (is-violated p1B))
		     (* 1 (is-violated p1C))
		     (* 1 (is-violated p1D))
		     (* 1 (is-violated p1E))
		     (* 1 (is-violated p1F))
		     (* 1 (is-violated p1G))
		     (* 1 (is-violated p1H))
		     (* 2 (is-violated p2A))
		     (* 2 (is-violated p2B))
		     (* 2 (is-violated p2C))
		     (* 2 (is-violated p2D))
		     (* 2 (is-violated p2E))
		     (* 2 (is-violated p2F))
		     (* 2 (is-violated p2G))
		     (* 2 (is-violated p2H))
		     (* 3 (is-violated p3A))
		     (* 3 (is-violated p3B))
		     (* 3 (is-violated p3C))
		     (* 3 (is-violated p3D))
		     (* 3 (is-violated p3E))
		     (* 3 (is-violated p3F))
		     (* 3 (is-violated p3G))
		     (* 3 (is-violated p3H))
		     (* 4 (is-violated p4A))
		     (* 4 (is-violated p4B))
		     (* 4 (is-violated p4C))
		     (* 4 (is-violated p4D))
		     (* 4 (is-violated p4E))
		     (* 4 (is-violated p4F))
		     (* 4 (is-violated p4G))
		     (* 4 (is-violated p4H))
		     (* 5 (is-violated p5A))
		     (* 5 (is-violated p5B))
		     (* 5 (is-violated p5C))
		     (* 5 (is-violated p5D))
		     (* 5 (is-violated p5E))
		     (* 5 (is-violated p5F))
		     (* 5 (is-violated p5G))
		     (* 5 (is-violated p5H))
		     (* 6 (is-violated p6A))
		     (* 6 (is-violated p6B))
		     (* 6 (is-violated p6C))
		     (* 6 (is-violated p6D))
		     (* 6 (is-violated p6E))
		     (* 6 (is-violated p6F))
		     (* 6 (is-violated p6G))
		     (* 6 (is-violated p6H))
		     (* 7 (is-violated p7A))
		     (* 7 (is-violated p7B))
		     (* 7 (is-violated p7C))
		     (* 7 (is-violated p7D))
		     (* 7 (is-violated p7E))
		     (* 7 (is-violated p7F))
		     (* 7 (is-violated p7G))
		     (* 7 (is-violated p7H))
		     (* 8 (is-violated p8A))
		     (* 8 (is-violated p8B))
		     (* 8 (is-violated p8C))
		     (* 8 (is-violated p8D))
		     (* 8 (is-violated p8E))
		     (* 8 (is-violated p8F))
		     (* 8 (is-violated p8G))
		     (* 8 (is-violated p8H))
		     (* 9 (is-violated p9A))
		     (* 9 (is-violated p9B))
		     (* 9 (is-violated p9C))
		     (* 9 (is-violated p9D))
		     (* 9 (is-violated p9E))
		     (* 9 (is-violated p9F))
		     (* 9 (is-violated p9G))
		     (* 9 (is-violated p9H))
		     (* 10 (is-violated p10A))
		     (* 10 (is-violated p10B))
		     (* 10 (is-violated p10C))
		     (* 10 (is-violated p10D))
		     (* 10 (is-violated p10E))
		     (* 10 (is-violated p10F))
		     (* 10 (is-violated p10G))
		     (* 10 (is-violated p10H))
		     (* 11 (is-violated p11A))
		     (* 11 (is-violated p11B))
		     (* 11 (is-violated p11C))
		     (* 11 (is-violated p11D))
		     (* 11 (is-violated p11E))
		     (* 11 (is-violated p11F))
		     (* 11 (is-violated p11G))
		     (* 11 (is-violated p11H))
		     (* 12 (is-violated p12A))
		     (* 12 (is-violated p12B))
		     (* 12 (is-violated p12C))
		     (* 12 (is-violated p12D))
		     (* 12 (is-violated p12E))
		     (* 12 (is-violated p12F))
		     (* 12 (is-violated p12G))
		     (* 12 (is-violated p12H))
		     (* 13 (is-violated p13A))
		     (* 13 (is-violated p13B))
		     (* 13 (is-violated p13C))
		     (* 13 (is-violated p13D))
		     (* 13 (is-violated p13E))
		     (* 13 (is-violated p13F))
		     (* 14 (is-violated p14A))
		     (* 14 (is-violated p14B))
		     (* 14 (is-violated p14C))
		     (* 14 (is-violated p14D))
		     (* 14 (is-violated p14E))
		     (* 14 (is-violated p14F))
		     (* 15 (is-violated p15A))
		     (* 15 (is-violated p15B))
		     (* 15 (is-violated p15C))
		     (* 15 (is-violated p15D))
		     (* 15 (is-violated p15E))
		     (* 15 (is-violated p15F))
		     (* 16 (is-violated p16A))
		     (* 16 (is-violated p16B))
		     (* 16 (is-violated p16C))
		     (* 17 (is-violated p17A))
		     (* 17 (is-violated p17B))
		     (* 17 (is-violated p17C))
		     (* 18 (is-violated p18A))
		     (* 18 (is-violated p18B))
		     (* 18 (is-violated p18C))))

)
