# Template generated code from trgen <version>
default:
	rm -rf build; mkdir build; cd build; cmake .. <cmake_target>; $(MAKE)
run:
	cd build; trwdog ./<exec_name> $(RUNARGS)
clean:
	rm -rf build <temp_dir>/antlr4_runtime
test:
	bash test.sh
