# Generated code from Antlr4BuildTasks.dotnet-antlr v <version>
default:
	rm -rf build; mkdir build; cd build; cmake .. <cmake_target>; $(MAKE)
run:
	cd build; ./<exec_name> $(RUNARGS)
clean:
	rm -rf build
test:
	bash test.sh
