	TITLE	'ASM COMMON DATA AREA'
;
;	COPYRIGHT (C) 1977, 1978
;	DIGITAL RESEARCH
;	BOX 579, PACIFIC GROVE
;	CALIFORNIA, 93950
;
;	COMMON DATA FOR CP/M ASSEMBLER MODULE
	ORG	100H
ENDA	EQU	20F0H	;END OF ASSEMBLER PROGRAM
BDOS	EQU	5H	;ENTRY TO DOS, USED TO COMPUTE END MEMORY
	LXI	SP,ENDMOD
	LHLD	BDOS+1
	SHLD	SYMAX	;COMPUTE END OF MEMORY
	JMP	ENDMOD
COPY:	DB	' COPYRIGHT(C) 1978, DIGITAL RESEARCH '
	ORG	COPY
;
;	PRINT BUFFER AND PRINT BUFFER POINTER
PBMAX	EQU	120	;MAX PRINT BUFFER
PBUFF:	DS	PBMAX
PBP:	DS	1	;PRINT BUFFER POINTER
;
;	SCANNER PARAMETERS
TOKEN:	DS	1	;CURRENT TOKEN
VALUE:	DS	2	;BINARY VALUE FOR NUMBERS
ACCLEN:	DS	1	;ACCUMULATOR LENGTH
ACMAX	EQU	64	;LENGTH OF ACCUMULATOR
ACCUM:	DS	ACMAX	;ACCUMULATOR (MUST FOLLLOW ACCLEN)
;
;	OPERAND EXPRESSION EVALUATOR PARAMETERS
EVALUE:	DS	2	;VALUE OF EXPRESSION AFTER EVALUATION
;
;	SYMBOL TABLE  MODULE PARAMETERS
SYTOP:	DW	ENDA	;FIRST LOCATION AVAILABLE FOR SYMBOL TABLE
SYMAX:	DS	2	;LAST AVAILABLE LOCATION FOR SYMBOL TABLE
;
;	MISCELLANEOUS DATA AREAS
PASS:	DS	1	;PASS # 0,1
FPC:	DS	2	;FILL ADDRESS FOR NEXT HEX RECORD
ASPC:	DS	2	;ASSEMBLER'S PSEUDO PC
SYBAS:	DW	ENDA	;SYMBOL TABLE BASE
SYADR:	DS	2	;CURRENT SYMBOL BASE
ENDMOD	EQU	($ AND 0FF00H)+100H
	END
