;
; DATE Generation
;
stat con:=tty:
vax $$as\sd mason.cpm30.sources\ar
vax date.plm $$stran
stat con:=uc1:
seteof date.plm
is14
plm80 date.plm pagewidth(100) debug optimize 
link mcd80a.obj,date.obj,plm80.lib to date.mod
locate date.mod code(0100H) stacksize(100)
era date.mod
cpm
zero
objcpm date
era date
era date.obj
stat con:=tty:
vax $$as\sd mason.cpm30.listing\ar
vax date.lst $$stran
stat con:=uc1:
era *.lst
era *.lin
era *.sym
;
; Call Next Submit
;
sub cpm3plm4
