 
	dcl
		memptr entry				returns (ptr),
		memsiz entry				returns (fixed(15)),
		memwds entry				returns (fixed(15)),
		dfcb0  entry				returns (ptr),
		dfcb1  entry				returns (ptr),
		dbuff  entry				returns (ptr),
		reboot entry,
		rdcon  entry				returns (char(1)),
		wrcon  entry	(char(1)),
		rdrdr  entry				returns (char(1)),
		wrpun  entry	(char(1)),
		wrlst  entry	(char(1)),
		coninp entry				returns (char(1)),
		conout entry	(char(1)),
		rdstat entry				returns (bit(1)),
		getio  entry				returns (bit(8)),
		setio  entry	(bit(8)),
		wrstr  entry	(ptr),
		rdbuf  entry	(ptr),
		break  entry				returns (bit(1)),
		vers   entry				returns (bit(16)),
		reset  entry,
		select entry	(fixed(7))	returns (bit(16)),
		open   entry	(ptr)		returns (bit(16)),
		close  entry	(ptr)		returns (bit(16)),
		sear   entry	(ptr)		returns (bit(16)),
		searn  entry				returns (bit(16)),
		delete entry	(ptr)		returns (bit(16)),
		rdseq  entry	(ptr)		returns (bit(16)),
		wrseq  entry	(ptr)		returns (bit(16)),
		make   entry	(ptr)		returns (bit(16)),
		rename entry	(ptr)		returns (bit(16)),
		logvec entry				returns (bit(16)),
		curdsk entry				returns (fixed(7)),
		setdma entry	(ptr),
		allvec entry				returns (ptr),
		wpdisk entry,
		rovec  entry				returns (bit(16)),
		filatt entry	(ptr),
		getdpb entry				returns (ptr),
		getusr entry				returns (fixed(7)),
		setusr entry	(fixed(7)),
		rdran  entry	(ptr)	  	returns (bit(16)),
		wrran  entry	(ptr)		returns (bit(16)),
		filsiz entry	(ptr),
		setrec entry	(ptr),
		resdrv entry	(bit(16))	returns (bit(16)),
		wrranz entry	(ptr)		returns (bit(16)),
		testwr entry	(ptr)		returns (bit(16)),
		lock   entry	(ptr)		returns (fixed(7)),
		unlock entry	(ptr)		returns (fixed(7)),
		multis entry	(fixed(7)) 	returns (fixed(7)),		
		ermode entry	(bit(1)),
		freesp entry	(fixed(7)) 	returns (bit(16)),		
		chain  entry				returns (bit(16)),		
		flush  entry			 	returns (fixed(7)),		
		setlbl entry	(ptr)		returns (bit(16)),
		getlbl entry	(fixed(7))	returns (bit(8)),
		rdxfcb entry	(ptr)		returns (bit(16)),
		wrxfcb entry	(ptr)		returns (bit(16)),
		settod entry	(ptr),
		gettod entry	(ptr),
		dfpswd entry	(ptr),
		sgscb  entry    (ptr) returns(bit(8));
