// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mna/pigeon/ast"
)

func (c *current) onGrammar1(initializer, rules any) (any, error) {
	rulesSlice := toAnySlice(rules)
	g.Rules = make([]*ast.Rule, len(rulesSlice))
	return g, nil
}
