element #book {"content"} ;
element {$name} {"value"} ;
attribute #class {"selected"} ;
attribute {$attrName} {$attrValue} ;
text {"hello world"} ;
comment {"a comment"} ;
document {text {"root"}} ;
namespace #ex {"http://example.com"} ;
namespace {$prefix} {$uri} ;
processing-instruction #xml-stylesheet {"type='text/xsl'"} ;
map{"name": "Alice", "age": 30} ;
["a", "b", "c"] ;
array{1 to 5} ;
