for $x in //item return $x/title ;
for $x in 1 to 10 return $x * $x ;
let $total := sum(//price) return $total ;
for $x in //book let $author := $x/author return concat($x/title, " by ", $author) ;
for $x in //item where $x/@price > 10 return $x ;
for $x in //book order by $x/title return $x ;
for $x in //book order by $x/price descending return $x ;
some $x in //item satisfies $x/@price > 100 ;
every $x in //item satisfies $x/@price > 0 ;
for $x in 1 to 5 for $y in 1 to 5 return $x * $y ;
for $x in //book order by $x/year ascending empty greatest return $x ;
for $x in //book stable order by $x/title return $x ;
for $x in 1 to 10 count $pos return concat($pos, ": ", $x) ;
let $x := 42 return $x ;
let $x as xs:integer := 10 return $x + 1 ;
for $x in //item let $name := string($x/@name) return $name ;
for member $m in [1, 2, 3] return $m * 2 ;
for value $v in map{"a": 1, "b": 2} return $v ;
for key $k value $v in map{"x": 10, "y": 20} return concat($k, "=", $v) ;
