$x instance of xs:integer ;
$x instance of xs:string? ;
$x instance of element() ;
$x instance of element(book) ;
$x instance of map(*) ;
$x instance of map(xs:string, xs:integer) ;
$x instance of array(*) ;
$x instance of array(xs:integer+) ;
$x instance of record(name as xs:string, age? as xs:integer) ;
$x instance of record(*) ;
$x instance of enum("red", "green", "blue") ;
$x instance of (xs:string | xs:integer) ;
$x instance of function(*) ;
$x instance of fn(xs:string) as xs:boolean ;
$x instance of gnode() ;
$x instance of jnode(*) ;
$x instance of jnode(number) ;
"hello" cast as xs:integer ;
$x castable as xs:date ;
$x treat as xs:string ;
$color cast as enum("small", "medium", "large") ;
