$title otherwise "untitled" ;
$a otherwise $b otherwise $c ;
$items =!> string() ;
(1, 2, 3) =!> xs:string() ;
$string => upper-case() => normalize-space() ;
$record +:= map{"name": "Alice"} ;
$r +:= map{"age": 30} ;
`Hello, world!` ;
`Count: {$n}` ;
`{$first} {$last}` ;
fn($x as xs:integer) { $x * 2 } ;
fn($x as xs:string, $y as xs:string) as xs:string { $x || $y } ;
format-date($date, picture := "[Y]-[M]-[D]") ;
substring($str, start := 1) ;
child::(element() | text()) ;
descendant::(h1 | h2 | h3) ;
if ($x gt 0) { $x } ;
fn:string#1 ;
upper-case#1 ;
