ALTER TABLE foo.t DROP COLUMN c;
ALTER TABLE "t x" DROP COLUMN "c d";
ALTER TABLE IF EXISTS foo.t DROP COLUMN c;
ALTER TABLE foo.t DROP COLUMN IF EXISTS c;
ALTER TABLE IF EXISTS foo.t DROP COLUMN IF EXISTS c;
