name: Perf analysis of what has changed
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      shell: bash
      run: |
        arch
        uname -a
        if [ -f /proc/cpuinfo ]; then cat /proc/cpuinfo; fi
    - name: Install Octave
      run: |
        sudo apt install octave
        sudo apt install octave-statistics
        octave --version
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'
    - name: Test Dotnet
      run: |
        dotnet --version
        dotnet --info
        dotnet --list-runtimes
        dotnet --list-sdks
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Test Java
      run: |
        dotnet --version
        java --version
        javac --version
    - name: Install Antlr tool
      run: |
         pip install antlr4-tools
    - name: Install JavaScript
      if: ${{ matrix.language == 'JavaScript' }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '16.13.0'
    - name: Test JavaScript
      if: ${{ matrix.language == 'JavaScript' }}
      run: |
        node --version
    - name: Update paths
      shell: pwsh
      run: |
        if ("${{ matrix.os }}" -eq "ubuntu-latest") {
            echo "$HOME/.dotnet/tools" >> $env:GITHUB_PATH
        }
    - name: Install Trash
      shell: bash
      run: |
        dotnet tool restore
    - name: Test Trash install
      shell: bash
      run: |
        dotnet trgen -- --help
    - name: Test
      shell: bash
      run: |
        if [ "${{github.event_name}}" == "pull_request" ] ; then
            Before="${{github.event.pull_request.base.sha}}"
            After="${{github.event.pull_request.head.sha}}"
        else
            Before="${{github.event.before}}"
            After="${{github.event.after}}"
        fi
        bash _scripts/perf-changed.sh -b "$Before" -a "$After"

