-- add options
ALTER FOREIGN SERVER Presto1 ADD VERSION('1.0');

ALTER FOREIGN SERVER Presto1 ADD IMPORT USING VERSION('1.0');

ALTER FOREIGN SERVER Presto1 ADD IMPORT WITH TD_SYSFNLIB.QGInitiatorImport;

ALTER FOREIGN SERVER Presto1 ADD IMPORT WITH TD_SYSFNLIB.QGInitiatorImport USING VERSION('1.0');

-- drop options
ALTER FOREIGN SERVER Presto1 DROP LINK;

ALTER FOREIGN SERVER Presto1 DROP IMPORT;

ALTER FOREIGN SERVER Presto1 DROP IMPORT USING VERSION LINK;
